# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='room_booked',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.HomeAssests'),
        ),
    ]
