# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeassests',
            name='availabilty',
            field=models.BooleanField(default=True),
        ),
    ]
