# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171222_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeassests',
            old_name='home_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='homeassests',
            name='rate_per_day',
            field=models.IntegerField(default=None),
        ),
    ]
