# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171222_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeassests',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
