# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_homeassests_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='renter_person',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.Renter'),
            preserve_default=False,
        ),
    ]
