# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookings_renter_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='room_booked',
        ),
        migrations.AddField(
            model_name='renter',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
